# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0013_auto_20161013_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfooter',
            name='company_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='company_hours',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_left',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_right',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_right_header',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
