# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0015_auto_20161024_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('menu', 'slug')]),
        ),
    ]
