# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0016_auto_20170222_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
