# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0017_headerfooter_company_name'),
        ('block', '0018_image_user'),
    ]

    operations = [
    ]
