# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 20:33
from __future__ import unicode_literals

import block.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('block', '0015_auto_20161024_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_moderated', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Test contents',
                'verbose_name': 'Test content',
            },
        ),
        migrations.CreateModel(
            name='TitleBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('page_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.PageSection')),
            ],
            options={
                'verbose_name_plural': 'Blocks',
                'verbose_name': 'Block',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_block.Title')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Image')),
            ],
            options={
                'verbose_name_plural': 'Title Images',
                'verbose_name': 'Title Image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TitleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_block.Title')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Link')),
            ],
            options={
                'verbose_name_plural': 'Title Links',
                'verbose_name': 'Title Link',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='title',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='example_block.TitleBlock'),
        ),
        migrations.AddField(
            model_name='title',
            name='edit_state',
            field=models.ForeignKey(default=block.models._default_edit_state, on_delete=django.db.models.deletion.CASCADE, to='block.EditState'),
        ),
        migrations.AddField(
            model_name='title',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_link', to='block.Link'),
        ),
        migrations.AddField(
            model_name='title',
            name='moderate_state',
            field=models.ForeignKey(default=block.models._default_moderate_state, on_delete=django.db.models.deletion.CASCADE, to='block.ModerateState'),
        ),
        migrations.AddField(
            model_name='title',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_picture', to='block.Image'),
        ),
        migrations.AddField(
            model_name='title',
            name='references',
            field=models.ManyToManyField(related_name='references', through='example_block.TitleLink', to='block.Link'),
        ),
        migrations.AddField(
            model_name='title',
            name='slideshow',
            field=models.ManyToManyField(related_name='slideshow', through='example_block.TitleImage', to='block.Image'),
        ),
        migrations.AddField(
            model_name='title',
            name='user_moderated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together=set([('block', 'moderate_state')]),
        ),
    ]
